version: "3"
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    environment:
      POSTGRES_USER: tomas
      POSTGRES_PASSWORD: test
      POSTGRES_DB: slack
  web:
    image: penthious/slack-clone-server:latest
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "index.js"]
    volumes:
      - ./files:/app/files
  nginx:
    image: nginx
    volumes:
     - ./site.template:/etc/nginx/conf.d/site.template
     - ./files:/files
    ports:
     - "8080:80"
    networks:
      - webnet
    depends_on:
      - web
    command: /bin/bash -c "cat < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
  webnet:
